disabled_rules:
  - large_tuple
  - function_body_length
  - cyclomatic_complexity
  - identifier_name
  - type_name
  - trailing_closure
  - explicit_acl
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - type_body_length
  - file_length

opt_in_rules:
  - force_unwrapping
  - force_try
  - unused_optional_binding
